server:
  port: 9992

spring:
  application:
    name: log-collection-consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}-test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    druid:
    url: jdbc:mysql://localhost:3306/log-collection?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: papupupu
    password: pppp
    driver-class-name: com.mysql.cj.jdbc.Driver